CREATE SCHEMA IF NOT EXISTS TEST1;

SET SCHEMA TEST1 ;

CREATE TABLE badge ( 
	code VARCHAR(2),
	name VARCHAR(45),
	PRIMARY KEY(code)
);


DROP TABLE CUSTOMER ;

ALTER TABLE country ADD COLUMN badge_code VARCHAR(2);
ALTER TABLE country ADD FOREIGN KEY(badge_code) REFERENCES badge(code) ;

